// Intelligence layer — code understanding, CLAUDE.md generation, repo analysis
// The agent reads its own repo and builds self-awareness

export class Intelligence {
  private kv: KVNamespace;

  constructor(kv: KVNamespace) {
    this.kv = kv;
  }

  // ===== Repo Analysis =====
  async analyzeRepo(files: Array<{ path: string; type: string }>): Promise<RepoAnalysis> {
    const languages = new Map<string, number>();
    const modules = new Map<string, string[]>();

    for (const file of files) {
      const ext = file.path.split('.').pop() || '';
      const lang = EXTENSION_MAP[ext] || 'unknown';
      languages.set(lang, (languages.get(lang) || 0) + 1);

      // Group by top-level directory
      const parts = file.path.split('/');
      if (parts.length > 1) {
        const module = parts.slice(0, 2).join('/');
        if (!modules.has(module)) modules.set(module, []);
        modules.get(module)!.push(file.path);
      }
    }

    return {
      totalFiles: files.length,
      languages: Object.fromEntries(languages),
      modules: Object.fromEntries(modules),
      hasTypeScript: languages.has('typescript'),
      hasReadme: files.some(f => f.path === 'README.md'),
      hasConfig: files.some(f => f.path === 'package.json' || f.path === 'tsconfig.json'),
    };
  }

  // ===== CLAUDE.md Generation =====
  async generateClaudeMd(
    analysis: RepoAnalysis,
    soul: { name: string; tone: string }
  ): Promise<string> {
    const langEntries = Object.entries(analysis.languages)
      .sort(([, a], [, b]) => b - a)
      .map(([lang, count]) => `- ${lang}: ${count} files`)
      .join('\n');

    const moduleEntries = Object.entries(analysis.modules)
      .map(([mod, files]) => `- ${mod}/ (${files.length} files)`)
      .join('\n');

    return `# CLAUDE.md — ${soul.name}

> Generated by ${soul.name} — ${new Date().toISOString()}

## Project Overview

This is a **personallog.ai** instance — a personal AI agent that lives in a repo.
Built on the cocapn paradigm: the repo IS the agent.

## Repository Structure

${moduleEntries}

## Language Breakdown

${langEntries}

## Architecture

- **Entry point**: \`src/worker.ts\` — Cloudflare Worker routing
- **Agent core**: \`src/agent/\` — Soul, memory, context, intelligence
- **Channels**: \`src/channels/\` — Telegram, Discord, WhatsApp connectors
- **Static**: \`public/\` — Landing page and web app
- **Config**: \`cocapn/\` — Soul and configuration files

## Key Conventions

- TypeScript strict mode, ESM modules
- Cloudflare Workers runtime (no Node.js APIs)
- KV for persistence (memory, facts, history)
- soul.md defines agent personality (edit to customize)
- Multi-channel: web, Telegram, Discord, WhatsApp

## Development

\`\`\`bash
npm install        # Install dependencies
npm run dev        # Local development (wrangler dev)
npm run deploy     # Deploy to Cloudflare Workers
npm run typecheck  # Type check
\`\`\`

## Agent Personality

- **Name**: ${soul.name}
- **Tone**: ${soul.tone}
- **Edit**: \`cocapn/soul.md\`
`;
  }

  // ===== Code Understanding =====
  async summarizeFile(path: string, content: string): Promise<FileSummary> {
    const lines = content.split('\n');
    const exports = lines
      .filter(l => l.includes('export '))
      .map(l => l.trim());

    const imports = lines
      .filter(l => l.includes('import '))
      .map(l => l.trim());

    const functions = lines
      .filter(l => /^(export\s+)?(async\s+)?function\s|const\s+\w+\s*=\s*(async\s*)?\(/.test(l))
      .map(l => l.trim());

    const classes = lines
      .filter(l => /^(export\s+)?class\s/.test(l))
      .map(l => l.trim());

    return {
      path,
      lines: lines.length,
      exports: exports.slice(0, 20),
      imports: imports.slice(0, 20),
      functions: functions.slice(0, 20),
      classes: classes.slice(0, 10),
      language: path.split('.').pop() || 'unknown',
    };
  }

  // ===== Self-Knowledge =====
  async buildSelfKnowledge(files: Array<{ path: string; type: string }>): Promise<string> {
    const analysis = await this.analyzeRepo(files);

    const parts: string[] = [
      `I am a personal AI agent running on Cloudflare Workers.`,
      `My repo contains ${analysis.totalFiles} files.`,
      `I speak ${Object.keys(analysis.languages).join(', ')}.`,
      `My code is organized into: ${Object.keys(analysis.modules).join(', ')}.`,
    ];

    if (analysis.hasTypeScript) {
      parts.push('I am written in TypeScript with strict mode enabled.');
    }

    if (analysis.hasReadme) {
      parts.push('I have a README that explains how to set me up.');
    }

    return parts.join(' ');
  }
}

// ===== Types =====
export interface RepoAnalysis {
  totalFiles: number;
  languages: Record<string, number>;
  modules: Record<string, string[]>;
  hasTypeScript: boolean;
  hasReadme: boolean;
  hasConfig: boolean;
}

export interface FileSummary {
  path: string;
  lines: number;
  exports: string[];
  imports: string[];
  functions: string[];
  classes: string[];
  language: string;
}

const EXTENSION_MAP: Record<string, string> = {
  ts: 'typescript',
  tsx: 'typescript',
  js: 'javascript',
  jsx: 'javascript',
  json: 'json',
  md: 'markdown',
  html: 'html',
  css: 'css',
  yml: 'yaml',
  yaml: 'yaml',
  toml: 'toml',
  sh: 'shell',
  py: 'python',
  go: 'go',
  rs: 'rust',
};
